<template>
            <v-row justify="center">
                <v-dialog
                v-model="dialog"
                persistent
                max-width="600px"
                >
                <v-card>
                    <v-card-title>
                    <span class="text-h5">Edicion de Producto</span>
                    </v-card-title>
                    <v-card-text>
                    <v-container>
                        <v-row>
                        <v-col
                            cols="12"
                            sm="8"
                            md="6"
                        >
                            <v-text-field
                            label="Codigo(*)"
                            required
                            type="number"
                            v-model="producto.codigo"
                            ></v-text-field>
                        </v-col>
                        <v-col
                            cols="12"
                            sm="8"
                            md="6"
                        >
                            <v-text-field
                            label="Descripcion(*)"
                            type="text"
                            arequired
                            v-model="producto.descripcion"
                            ></v-text-field>
                        </v-col>
                        
                        </v-row>
                        <v-row>
                            <v-col
                            cols="12"
                            sm="8"
                            md="6">
                            <v-text-field 
                            label="Precio(*)" 
                            type="number" 
                            step="0.01" 
                            v-model="producto.precio" 
                            required></v-text-field>
                            </v-col>
                            <v-col
                            cols="12"
                            sm="8"
                            md="6">
                            <v-text-field 
                            label="Cantidad(*)" 
                            type="number"  
                            v-model="producto.cantidad" 
                            required></v-text-field>
                            </v-col>
                        </v-row>
                    </v-container>
                    <small>(*)Campos Requeridos</small>
                    </v-card-text>
                    <v-card-actions>
                    <v-spacer></v-spacer>
                    <v-btn
                        color="blue darken-1"
                        text
                        @click="dialog = false"
                    >
                        Cerrar
                    </v-btn>
                    <v-btn
                        color="blue darken-1"
                        text
                        @click="modificarProducto()"
                    >
                        Modificar
                    </v-btn>
                    </v-card-actions>
                </v-card>
                </v-dialog>
            </v-row>
            </template>